import { ThemeConfig, ThemeName } from "./types";

export const themes: Record<ThemeName, ThemeConfig> = {
  cyborg: {
    name: "cyborg",
    label: "Cyborg",
    description: "Teknologi futuristik dengan elemen mekanik",
    colors: {
      primary: "#00f0ff",
      secondary: "#7b2ff7",
      accent: "#ff0080",
      background: "#0a0e17",
      surface: "#111827",
      text: "#e0f7fa",
      textMuted: "#607d8b",
      border: "#1e3a5f",
      glow: "#00f0ff",
      gradient: "linear-gradient(135deg, #0a0e17 0%, #1a1a2e 50%, #16213e 100%)",
    },
    font: "var(--font-geist-mono)",
    loadingStyle: "matrix-rain",
  },
  samurai: {
    name: "samurai",
    label: "Samurai",
    description: "Elegansi feudal Jepang dengan sentuhan modern",
    colors: {
      primary: "#dc143c",
      secondary: "#c9b037",
      accent: "#f5f5dc",
      background: "#0d0d0d",
      surface: "#1a1a1a",
      text: "#f5f5dc",
      textMuted: "#8b7355",
      border: "#3d2b1f",
      glow: "#dc143c",
      gradient: "linear-gradient(135deg, #0d0d0d 0%, #1a0a0a 50%, #2d1b1b 100%)",
    },
    font: "var(--font-geist-sans)",
    loadingStyle: "enso-circle",
  },
  aurora: {
    name: "aurora",
    label: "Aurora",
    description: "Kehangatan cahaya utara yang memukau",
    colors: {
      primary: "#00e5a0",
      secondary: "#7b68ee",
      accent: "#ff6b9d",
      background: "#0b0c2a",
      surface: "#141538",
      text: "#e8f4f8",
      textMuted: "#7b8cde",
      border: "#2a2d5e",
      glow: "#00e5a0",
      gradient: "linear-gradient(135deg, #0b0c2a 0%, #1a0533 30%, #0d2137 60%, #0b0c2a 100%)",
    },
    font: "var(--font-geist-sans)",
    loadingStyle: "aurora-waves",
  },
  marvel: {
    name: "marvel",
    label: "Marvel",
    description: "Dunia superhero yang penuh aksi",
    colors: {
      primary: "#e62429",
      secondary: "#0057a8",
      accent: "#ffd700",
      background: "#0f0f0f",
      surface: "#1c1c1c",
      text: "#ffffff",
      textMuted: "#a0a0a0",
      border: "#333333",
      glow: "#e62429",
      gradient: "linear-gradient(135deg, #0f0f0f 0%, #1a0000 50%, #000a1a 100%)",
    },
    font: "var(--font-geist-sans)",
    loadingStyle: "comic-burst",
  },
  medieval: {
    name: "medieval",
    label: "Abad Pertengahan",
    description: "Kastil, pedang, dan kehormatan ksatria",
    colors: {
      primary: "#c9a84c",
      secondary: "#8b4513",
      accent: "#b22222",
      background: "#1a1208",
      surface: "#2a1f10",
      text: "#e8d5a3",
      textMuted: "#8b7355",
      border: "#4a3728",
      glow: "#c9a84c",
      gradient: "linear-gradient(135deg, #1a1208 0%, #2d1f0e 50%, #1a1510 100%)",
    },
    font: "var(--font-geist-sans)",
    loadingStyle: "shield-reveal",
  },
  cyberpunk: {
    name: "cyberpunk",
    label: "Cyberpunk",
    description: "Masa depan yang gelap dan neon",
    colors: {
      primary: "#fcee09",
      secondary: "#ff003c",
      accent: "#00ff41",
      background: "#0a0a0a",
      surface: "#141414",
      text: "#f0f0f0",
      textMuted: "#666666",
      border: "#2a2a2a",
      glow: "#fcee09",
      gradient: "linear-gradient(135deg, #0a0a0a 0%, #1a0022 50%, #000a1a 100%)",
    },
    font: "var(--font-geist-mono)",
    loadingStyle: "neon-grid",
  },
  space: {
    name: "space",
    label: "Outer Space",
    description: "Ketidakpastian galaksi yang luas",
    colors: {
      primary: "#4fc3f7",
      secondary: "#7c4dff",
      accent: "#ff6e40",
      background: "#050510",
      surface: "#0d0d2b",
      text: "#e3f2fd",
      textMuted: "#5c6bc0",
      border: "#1a1a4e",
      glow: "#4fc3f7",
      gradient: "linear-gradient(135deg, #050510 0%, #0d0d2b 50%, #1a0a2e 100%)",
    },
    font: "var(--font-geist-mono)",
    loadingStyle: "starfield-warp",
  },
  nature: {
    name: "nature",
    label: "Nature",
    description: "Ketenangan alam dan kehidupan",
    colors: {
      primary: "#66bb6a",
      secondary: "#26a69a",
      accent: "#ffca28",
      background: "#0a1a0a",
      surface: "#132113",
      text: "#e8f5e9",
      textMuted: "#81c784",
      border: "#2e4a2e",
      glow: "#66bb6a",
      gradient: "linear-gradient(135deg, #0a1a0a 0%, #0d2818 50%, #1a2f1a 100%)",
    },
    font: "var(--font-geist-sans)",
    loadingStyle: "growing-vine",
  },
  "deep-ocean": {
    name: "deep-ocean",
    label: "Deep Ocean",
    description: "Kedalaman laut yang misterius",
    colors: {
      primary: "#00bcd4",
      secondary: "#0288d1",
      accent: "#76ff03",
      background: "#020e1a",
      surface: "#0a1929",
      text: "#b2ebf2",
      textMuted: "#4dd0e1",
      border: "#0d3b5e",
      glow: "#00bcd4",
      gradient: "linear-gradient(135deg, #020e1a 0%, #071a2e 50%, #0a2540 100%)",
    },
    font: "var(--font-geist-sans)",
    loadingStyle: "bubble-rise",
  },
  volcanic: {
    name: "volcanic",
    label: "Volcanic",
    description: "Kekuatan magma yang mengamuk",
    colors: {
      primary: "#ff5722",
      secondary: "#ff9800",
      accent: "#ffeb3b",
      background: "#1a0a00",
      surface: "#2d1500",
      text: "#fbe9e7",
      textMuted: "#ff8a65",
      border: "#5d2600",
      glow: "#ff5722",
      gradient: "linear-gradient(135deg, #1a0a00 0%, #2d0a00 50%, #1a1000 100%)",
    },
    font: "var(--font-geist-sans)",
    loadingStyle: "lava-flow",
  },
};

export function getTheme(name: ThemeName): ThemeConfig {
  return themes[name] || themes.cyborg;
}

export function getThemeCSSVars(theme: ThemeConfig): Record<string, string> {
  return {
    "--theme-primary": theme.colors.primary,
    "--theme-secondary": theme.colors.secondary,
    "--theme-accent": theme.colors.accent,
    "--theme-bg": theme.colors.background,
    "--theme-surface": theme.colors.surface,
    "--theme-text": theme.colors.text,
    "--theme-text-muted": theme.colors.textMuted,
    "--theme-border": theme.colors.border,
    "--theme-glow": theme.colors.glow,
    "--theme-gradient": theme.colors.gradient,
  };
}
